spring:

  application:
    name: life-up
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: life_up
        show_sql: true
  security.oauth2.client.registration.google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    com:
      khoavm:
        lifeup: DEBUG
#  pattern:
#    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
jwt:
  secret: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"

client:
  url: "http://localhost:4000"
